name: Run tests and upload coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests with pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff

      - name: Create virtual environment
        run: uv venv .venv

      - name: Add venv to PATH (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Add venv to PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          "VIRTUAL_ENV=.venv" >> $env:GITHUB_ENV
          "$pwd\.venv\Scripts" >> $env:GITHUB_PATH

      - name: Install dependencies
        run: make install-no-pre-commit

      - name: Run tests under coverage
        shell: bash
        run: |
          coverage run --source=model2vec -m pytest
          coverage report

      - name: Upload results to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
